name: TeamsPlus
version: '1.0.0'
main: com.vitaldev.teamsplus.TeamsPlus
api-version: '1.13'
depend:
  - DecentHolograms
softdepend:
  - PlaceholderAPI
  - RoseStacker
  - LifestealPlus
  - Vault
  - DiscordSRV
